receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:
    timeout: 5s
    send_batch_size: 1000
    send_batch_max_size: 2000

  memory_limiter:
    check_interval: 1s
    limit_mib: 256
    spike_limit_mib: 64

exporters:
  kafka/traces:
    brokers:
      - kafka:29092
    topic: traces.application
    protocol_version: "2.0.0"
    encoding: otlp_proto

  kafka/metrics:
    brokers:
      - kafka:29092
    topic: metrics.application
    protocol_version: "2.0.0"
    encoding: otlp_proto

  debug:
    verbosity: basic
    sampling_initial: 5
    sampling_thereafter: 200

extensions:
  health_check:
    endpoint: 0.0.0.0:13133

service:
  extensions: [health_check]

  pipelines:
    traces:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [kafka/traces, debug]

    metrics:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [kafka/metrics, debug]

  telemetry:
    logs:
      level: info
